### ISSUE TITLE
Collect DC use cases and and design guidelines of relevance to enrichment in cloud

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-api#7]
Monitor this repo: https://github.com/dcppc/design-guidelines/issues and tag here

 * [ ] Landscape of coronary artery disease https://github.com/dcppc/design-guidelines/issues/6 "He also identifies differentially enriched GO biological processes (BP) and molecular functions (MF), and the genes and phenotypes associated with these genes across all of the AGR genomes of interest"
 * [ ] Extend RNAseq case: https://github.com/dcppc/design-guidelines/issues/13 to do an enrichment analysis and deposit results and findings as bdbag

[everyone, edit this list and add more]

**Comment by pgaudet** [comment]
This repo does not exist anymore. Please reopen if you find another version of the repo (and if this work is still needed)
